# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fed24mari
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai-booking-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  createBooking:
    handler: functions/createBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post
  getBooking:
    handler: handler.getBooking
    events:
      - httpApi:
          path: /bookings/{id}
          method: get
  updateBooking:
    handler: handler.updateBooking
    events:
      - httpApi:
          path: /bookings/{id}
          method: put
  cancelBooking:
    handler: handler.cancelBooking
    events:
      - httpApi:
          path: /bookings/{id}
          method: delete
  listBookings:
    handler: handler.listBookings
    events:
      - httpApi:
          path: /bookings
          method: get
