# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fed24mari
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai-booking-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::605941533091:role/LambdaDynamoDBRol
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  createBooking:
    handler: functions/createBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post
  getBooking:
    handler: functions/getBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: get
  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: put
  cancelBooking:
    handler: functions/cancelBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: delete
  listBookings:
    handler: functions/listBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get

resources:
  Resources:
    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BonzaiBookings
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
